// Code generated by protoc-gen-go. DO NOT EDIT.
// source: RecommendationService.proto

package RecommendationService

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// contentTile
type TileType int32

const (
	TileType_ImageTile     TileType = 0
	TileType_VideoTile     TileType = 1
	TileType_FeatureTile   TileType = 2
	TileType_AdvertiseTile TileType = 3
	TileType_CarouselTile  TileType = 4
)

var TileType_name = map[int32]string{
	0: "ImageTile",
	1: "VideoTile",
	2: "FeatureTile",
	3: "AdvertiseTile",
	4: "CarouselTile",
}

var TileType_value = map[string]int32{
	"ImageTile":     0,
	"VideoTile":     1,
	"FeatureTile":   2,
	"AdvertiseTile": 3,
	"CarouselTile":  4,
}

func (x TileType) String() string {
	return proto.EnumName(TileType_name, int32(x))
}

func (TileType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_abcf9f213a14e9af, []int{0}
}

type TileClickedRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	TileId               string   `protobuf:"bytes,2,opt,name=tileId,proto3" json:"tileId,omitempty"`
	TileScore            float64  `protobuf:"fixed64,3,opt,name=tileScore,proto3" json:"tileScore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TileClickedRequest) Reset()         { *m = TileClickedRequest{} }
func (m *TileClickedRequest) String() string { return proto.CompactTextString(m) }
func (*TileClickedRequest) ProtoMessage()    {}
func (*TileClickedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_abcf9f213a14e9af, []int{0}
}

func (m *TileClickedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TileClickedRequest.Unmarshal(m, b)
}
func (m *TileClickedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TileClickedRequest.Marshal(b, m, deterministic)
}
func (m *TileClickedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TileClickedRequest.Merge(m, src)
}
func (m *TileClickedRequest) XXX_Size() int {
	return xxx_messageInfo_TileClickedRequest.Size(m)
}
func (m *TileClickedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TileClickedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TileClickedRequest proto.InternalMessageInfo

func (m *TileClickedRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TileClickedRequest) GetTileId() string {
	if m != nil {
		return m.TileId
	}
	return ""
}

func (m *TileClickedRequest) GetTileScore() float64 {
	if m != nil {
		return m.TileScore
	}
	return 0
}

type InitRecommendationRequest struct {
	Genres               []string `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`
	Categories           []string `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	Languages            []string `protobuf:"bytes,3,rep,name=languages,proto3" json:"languages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitRecommendationRequest) Reset()         { *m = InitRecommendationRequest{} }
func (m *InitRecommendationRequest) String() string { return proto.CompactTextString(m) }
func (*InitRecommendationRequest) ProtoMessage()    {}
func (*InitRecommendationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_abcf9f213a14e9af, []int{1}
}

func (m *InitRecommendationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRecommendationRequest.Unmarshal(m, b)
}
func (m *InitRecommendationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRecommendationRequest.Marshal(b, m, deterministic)
}
func (m *InitRecommendationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRecommendationRequest.Merge(m, src)
}
func (m *InitRecommendationRequest) XXX_Size() int {
	return xxx_messageInfo_InitRecommendationRequest.Size(m)
}
func (m *InitRecommendationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRecommendationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitRecommendationRequest proto.InternalMessageInfo

func (m *InitRecommendationRequest) GetGenres() []string {
	if m != nil {
		return m.Genres
	}
	return nil
}

func (m *InitRecommendationRequest) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *InitRecommendationRequest) GetLanguages() []string {
	if m != nil {
		return m.Languages
	}
	return nil
}

type InitRecommendationResponse struct {
	IsDone               bool     `protobuf:"varint,1,opt,name=isDone,proto3" json:"isDone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitRecommendationResponse) Reset()         { *m = InitRecommendationResponse{} }
func (m *InitRecommendationResponse) String() string { return proto.CompactTextString(m) }
func (*InitRecommendationResponse) ProtoMessage()    {}
func (*InitRecommendationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_abcf9f213a14e9af, []int{2}
}

func (m *InitRecommendationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRecommendationResponse.Unmarshal(m, b)
}
func (m *InitRecommendationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRecommendationResponse.Marshal(b, m, deterministic)
}
func (m *InitRecommendationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRecommendationResponse.Merge(m, src)
}
func (m *InitRecommendationResponse) XXX_Size() int {
	return xxx_messageInfo_InitRecommendationResponse.Size(m)
}
func (m *InitRecommendationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRecommendationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitRecommendationResponse proto.InternalMessageInfo

func (m *InitRecommendationResponse) GetIsDone() bool {
	if m != nil {
		return m.IsDone
	}
	return false
}

type GetRecommendationRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecommendationRequest) Reset()         { *m = GetRecommendationRequest{} }
func (m *GetRecommendationRequest) String() string { return proto.CompactTextString(m) }
func (*GetRecommendationRequest) ProtoMessage()    {}
func (*GetRecommendationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_abcf9f213a14e9af, []int{3}
}

func (m *GetRecommendationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecommendationRequest.Unmarshal(m, b)
}
func (m *GetRecommendationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecommendationRequest.Marshal(b, m, deterministic)
}
func (m *GetRecommendationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecommendationRequest.Merge(m, src)
}
func (m *GetRecommendationRequest) XXX_Size() int {
	return xxx_messageInfo_GetRecommendationRequest.Size(m)
}
func (m *GetRecommendationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecommendationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecommendationRequest proto.InternalMessageInfo

func (m *GetRecommendationRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type TileClickedResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TileClickedResponse) Reset()         { *m = TileClickedResponse{} }
func (m *TileClickedResponse) String() string { return proto.CompactTextString(m) }
func (*TileClickedResponse) ProtoMessage()    {}
func (*TileClickedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_abcf9f213a14e9af, []int{4}
}

func (m *TileClickedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TileClickedResponse.Unmarshal(m, b)
}
func (m *TileClickedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TileClickedResponse.Marshal(b, m, deterministic)
}
func (m *TileClickedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TileClickedResponse.Merge(m, src)
}
func (m *TileClickedResponse) XXX_Size() int {
	return xxx_messageInfo_TileClickedResponse.Size(m)
}
func (m *TileClickedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TileClickedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TileClickedResponse proto.InternalMessageInfo

func (m *TileClickedResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ContentTile struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	MediaUrl             string   `protobuf:"bytes,2,opt,name=mediaUrl,proto3" json:"mediaUrl,omitempty"`
	TileType             TileType `protobuf:"varint,3,opt,name=tileType,proto3,enum=RecommendationService.TileType" json:"tileType,omitempty"`
	Poster               string   `protobuf:"bytes,4,opt,name=poster,proto3" json:"poster,omitempty"`
	Portrait             string   `protobuf:"bytes,5,opt,name=portrait,proto3" json:"portrait,omitempty"`
	IsDetailPage         bool     `protobuf:"varint,6,opt,name=isDetailPage,proto3" json:"isDetailPage,omitempty"`
	PackageName          string   `protobuf:"bytes,7,opt,name=packageName,proto3" json:"packageName,omitempty"`
	ContentId            string   `protobuf:"bytes,8,opt,name=contentId,proto3" json:"contentId,omitempty"`
	Target               []string `protobuf:"bytes,9,rep,name=target,proto3" json:"target,omitempty"`
	RealeaseDate         string   `protobuf:"bytes,10,opt,name=realeaseDate,proto3" json:"realeaseDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContentTile) Reset()         { *m = ContentTile{} }
func (m *ContentTile) String() string { return proto.CompactTextString(m) }
func (*ContentTile) ProtoMessage()    {}
func (*ContentTile) Descriptor() ([]byte, []int) {
	return fileDescriptor_abcf9f213a14e9af, []int{5}
}

func (m *ContentTile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentTile.Unmarshal(m, b)
}
func (m *ContentTile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentTile.Marshal(b, m, deterministic)
}
func (m *ContentTile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentTile.Merge(m, src)
}
func (m *ContentTile) XXX_Size() int {
	return xxx_messageInfo_ContentTile.Size(m)
}
func (m *ContentTile) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentTile.DiscardUnknown(m)
}

var xxx_messageInfo_ContentTile proto.InternalMessageInfo

func (m *ContentTile) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ContentTile) GetMediaUrl() string {
	if m != nil {
		return m.MediaUrl
	}
	return ""
}

func (m *ContentTile) GetTileType() TileType {
	if m != nil {
		return m.TileType
	}
	return TileType_ImageTile
}

func (m *ContentTile) GetPoster() string {
	if m != nil {
		return m.Poster
	}
	return ""
}

func (m *ContentTile) GetPortrait() string {
	if m != nil {
		return m.Portrait
	}
	return ""
}

func (m *ContentTile) GetIsDetailPage() bool {
	if m != nil {
		return m.IsDetailPage
	}
	return false
}

func (m *ContentTile) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *ContentTile) GetContentId() string {
	if m != nil {
		return m.ContentId
	}
	return ""
}

func (m *ContentTile) GetTarget() []string {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *ContentTile) GetRealeaseDate() string {
	if m != nil {
		return m.RealeaseDate
	}
	return ""
}

func init() {
	proto.RegisterEnum("RecommendationService.TileType", TileType_name, TileType_value)
	proto.RegisterType((*TileClickedRequest)(nil), "RecommendationService.TileClickedRequest")
	proto.RegisterType((*InitRecommendationRequest)(nil), "RecommendationService.InitRecommendationRequest")
	proto.RegisterType((*InitRecommendationResponse)(nil), "RecommendationService.InitRecommendationResponse")
	proto.RegisterType((*GetRecommendationRequest)(nil), "RecommendationService.GetRecommendationRequest")
	proto.RegisterType((*TileClickedResponse)(nil), "RecommendationService.TileClickedResponse")
	proto.RegisterType((*ContentTile)(nil), "RecommendationService.ContentTile")
}

func init() { proto.RegisterFile("RecommendationService.proto", fileDescriptor_abcf9f213a14e9af) }

var fileDescriptor_abcf9f213a14e9af = []byte{
	// 649 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xbd, 0x6e, 0x53, 0x31,
	0x14, 0xe6, 0x26, 0xfd, 0x49, 0x4e, 0x5a, 0x68, 0xdd, 0x02, 0x6e, 0x5a, 0xda, 0xc8, 0x62, 0x28,
	0x19, 0x9a, 0x52, 0x98, 0xca, 0x84, 0x12, 0x5a, 0x65, 0x41, 0x28, 0x2d, 0x8c, 0x48, 0xce, 0xbd,
	0x47, 0x57, 0x56, 0x1d, 0x3b, 0xb5, 0x9d, 0x4a, 0x0c, 0x2c, 0xec, 0x4c, 0x3c, 0x00, 0x2b, 0x8f,
	0x83, 0xc4, 0x2b, 0xf0, 0x06, 0xbc, 0x00, 0xb2, 0x7d, 0xdb, 0x24, 0x22, 0xa9, 0x60, 0x60, 0xbb,
	0xdf, 0x77, 0x7c, 0xfc, 0x7d, 0xe7, 0xe7, 0x1a, 0xb6, 0x7b, 0x98, 0xea, 0xc1, 0x00, 0x55, 0xc6,
	0x9d, 0xd0, 0xea, 0x0c, 0xcd, 0x95, 0x48, 0xf1, 0x60, 0x68, 0xb4, 0xd3, 0xe4, 0xfe, 0xcc, 0x60,
	0x7d, 0x27, 0xd7, 0x3a, 0x97, 0xd8, 0xe2, 0x43, 0xd1, 0xe2, 0x4a, 0x69, 0x17, 0xa2, 0x36, 0x26,
	0xb1, 0x3e, 0x90, 0x73, 0x21, 0xb1, 0x2d, 0x45, 0x7a, 0x81, 0x59, 0x0f, 0x2f, 0x47, 0x68, 0x1d,
	0x79, 0x00, 0x4b, 0x23, 0x8b, 0xa6, 0x9b, 0xd1, 0xa4, 0x91, 0xec, 0x57, 0x7b, 0x05, 0xf2, 0xbc,
	0x13, 0x12, 0xbb, 0x19, 0x2d, 0x45, 0x3e, 0x22, 0xb2, 0x03, 0x55, 0xff, 0x75, 0x96, 0x6a, 0x83,
	0xb4, 0xdc, 0x48, 0xf6, 0x93, 0xde, 0x98, 0x60, 0x97, 0xb0, 0xd5, 0x55, 0xc2, 0x4d, 0xdb, 0x9b,
	0x90, 0xca, 0x51, 0x19, 0xb4, 0x34, 0x69, 0x94, 0xfd, 0x95, 0x11, 0x91, 0x5d, 0x80, 0x94, 0x3b,
	0xcc, 0xb5, 0x11, 0x68, 0x69, 0x29, 0xc4, 0x26, 0x18, 0x2f, 0x29, 0xb9, 0xca, 0x47, 0x3c, 0x47,
	0x4b, 0xcb, 0x21, 0x3c, 0x26, 0xd8, 0x73, 0xa8, 0xcf, 0x92, 0xb4, 0x43, 0xad, 0x2c, 0x7a, 0x4d,
	0x61, 0x3b, 0x5a, 0x61, 0x28, 0xaf, 0xd2, 0x2b, 0x10, 0x3b, 0x02, 0x7a, 0x8a, 0xf3, 0x7d, 0xce,
	0x6a, 0x09, 0x6b, 0xc1, 0xc6, 0x54, 0x03, 0x0b, 0x09, 0x0a, 0xcb, 0x76, 0x94, 0xa6, 0x68, 0x6d,
	0xa1, 0x71, 0x0d, 0xd9, 0xf7, 0x12, 0xd4, 0xda, 0x5a, 0x39, 0x54, 0xce, 0x27, 0x92, 0x4d, 0x58,
	0x74, 0xc2, 0x49, 0x2c, 0xee, 0x8d, 0x80, 0xd4, 0xa1, 0x32, 0xc0, 0x4c, 0xf0, 0xb7, 0x46, 0x16,
	0xbd, 0xbe, 0xc1, 0xe4, 0x05, 0x54, 0x7c, 0x73, 0xcf, 0x3f, 0x0c, 0x63, 0xb3, 0xef, 0x1e, 0xed,
	0x1d, 0xcc, 0x5e, 0x8c, 0xf3, 0xe2, 0x58, 0xef, 0x26, 0xc1, 0xd7, 0x31, 0xd4, 0xd6, 0xa1, 0xa1,
	0x0b, 0xb1, 0x8e, 0x88, 0xbc, 0xe0, 0x50, 0x1b, 0x67, 0xb8, 0x70, 0x74, 0x31, 0x0a, 0x5e, 0x63,
	0xc2, 0x60, 0x45, 0xd8, 0x0e, 0x3a, 0x2e, 0xe4, 0x1b, 0x9e, 0x23, 0x5d, 0x0a, 0x15, 0x4d, 0x71,
	0xa4, 0x01, 0xb5, 0x21, 0x4f, 0x2f, 0x78, 0x8e, 0xaf, 0xf9, 0x00, 0xe9, 0x72, 0xb8, 0x62, 0x92,
	0xf2, 0x13, 0x4b, 0x63, 0xdd, 0xdd, 0x8c, 0x56, 0x42, 0x7c, 0x4c, 0x84, 0xd5, 0xe2, 0x26, 0x47,
	0x47, 0xab, 0x71, 0x0f, 0x22, 0xf2, 0xda, 0x06, 0xb9, 0x44, 0x6e, 0xb1, 0xc3, 0x1d, 0x52, 0x08,
	0x89, 0x53, 0x5c, 0xf3, 0x3d, 0x54, 0xae, 0x2b, 0x25, 0xab, 0x50, 0xed, 0x0e, 0x78, 0x8e, 0x9e,
	0x58, 0xbb, 0xe3, 0xe1, 0x3b, 0x91, 0xa1, 0x0e, 0x30, 0x21, 0xf7, 0xa0, 0x76, 0x82, 0xdc, 0x8d,
	0x4c, 0x8c, 0x97, 0xc8, 0x3a, 0xac, 0xbe, 0xcc, 0xae, 0xd0, 0x38, 0x61, 0x23, 0x55, 0x26, 0x6b,
	0xb0, 0xd2, 0xe6, 0x46, 0x8f, 0x2c, 0xca, 0xc0, 0x2c, 0x1c, 0xfd, 0x5a, 0x80, 0xd9, 0x3f, 0x17,
	0xf9, 0x08, 0xb5, 0x89, 0xe9, 0x93, 0x27, 0xb7, 0xcc, 0x61, 0xfa, 0x17, 0xab, 0x37, 0xff, 0xe6,
	0x68, 0x5c, 0x26, 0xf6, 0xf0, 0xd3, 0x8f, 0x9f, 0x5f, 0x4a, 0xeb, 0x6c, 0xa5, 0xe5, 0xc6, 0xd1,
	0xe3, 0xa4, 0x49, 0xbe, 0x26, 0xb0, 0x73, 0x8a, 0xae, 0xad, 0xa5, 0xe4, 0x7d, 0xc3, 0x9d, 0xb8,
	0xc2, 0x13, 0x21, 0x1d, 0x1a, 0xa1, 0xf2, 0x0e, 0x77, 0x9c, 0xb4, 0xe6, 0xa8, 0xcc, 0x5b, 0xf3,
	0x3a, 0x9b, 0x93, 0x30, 0xb1, 0xb1, 0x6c, 0x3f, 0xd8, 0x61, 0xec, 0x51, 0x2b, 0xbf, 0x45, 0xfb,
	0x38, 0x69, 0x1e, 0x26, 0xe4, 0x73, 0x02, 0x1b, 0xc1, 0x61, 0x48, 0xef, 0x73, 0x8b, 0xd9, 0xff,
	0x33, 0xb6, 0x17, 0x8c, 0x6d, 0xb1, 0xcd, 0x68, 0x6c, 0x5a, 0x32, 0xfa, 0xf9, 0x96, 0xc0, 0xb6,
	0x7f, 0x19, 0x04, 0x97, 0xd3, 0xf7, 0xbd, 0x52, 0xb9, 0x50, 0x48, 0x0e, 0xe7, 0xc8, 0xcc, 0x7d,
	0xc0, 0xea, 0x4f, 0xff, 0x21, 0xa3, 0x98, 0xe7, 0xe3, 0xe0, 0x73, 0x97, 0x6d, 0xb5, 0xc4, 0x1f,
	0x87, 0xa2, 0x8f, 0xe3, 0xa4, 0xd9, 0x5f, 0x0a, 0x2f, 0xf4, 0xb3, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xb0, 0x6d, 0x6e, 0xc7, 0xf5, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecommendationServiceClient is the client API for RecommendationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecommendationServiceClient interface {
	TileClicked(ctx context.Context, in *TileClickedRequest, opts ...grpc.CallOption) (*TileClickedResponse, error)
	GetCollabrativeFilteringData(ctx context.Context, in *GetRecommendationRequest, opts ...grpc.CallOption) (RecommendationService_GetCollabrativeFilteringDataClient, error)
	GetContentbasedData(ctx context.Context, in *GetRecommendationRequest, opts ...grpc.CallOption) (RecommendationService_GetContentbasedDataClient, error)
	InitialRecommendationEngine(ctx context.Context, in *InitRecommendationRequest, opts ...grpc.CallOption) (*InitRecommendationResponse, error)
}

type recommendationServiceClient struct {
	cc *grpc.ClientConn
}

func NewRecommendationServiceClient(cc *grpc.ClientConn) RecommendationServiceClient {
	return &recommendationServiceClient{cc}
}

func (c *recommendationServiceClient) TileClicked(ctx context.Context, in *TileClickedRequest, opts ...grpc.CallOption) (*TileClickedResponse, error) {
	out := new(TileClickedResponse)
	err := c.cc.Invoke(ctx, "/RecommendationService.RecommendationService/TileClicked", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) GetCollabrativeFilteringData(ctx context.Context, in *GetRecommendationRequest, opts ...grpc.CallOption) (RecommendationService_GetCollabrativeFilteringDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RecommendationService_serviceDesc.Streams[0], "/RecommendationService.RecommendationService/GetCollabrativeFilteringData", opts...)
	if err != nil {
		return nil, err
	}
	x := &recommendationServiceGetCollabrativeFilteringDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RecommendationService_GetCollabrativeFilteringDataClient interface {
	Recv() (*ContentTile, error)
	grpc.ClientStream
}

type recommendationServiceGetCollabrativeFilteringDataClient struct {
	grpc.ClientStream
}

func (x *recommendationServiceGetCollabrativeFilteringDataClient) Recv() (*ContentTile, error) {
	m := new(ContentTile)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *recommendationServiceClient) GetContentbasedData(ctx context.Context, in *GetRecommendationRequest, opts ...grpc.CallOption) (RecommendationService_GetContentbasedDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RecommendationService_serviceDesc.Streams[1], "/RecommendationService.RecommendationService/GetContentbasedData", opts...)
	if err != nil {
		return nil, err
	}
	x := &recommendationServiceGetContentbasedDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RecommendationService_GetContentbasedDataClient interface {
	Recv() (*ContentTile, error)
	grpc.ClientStream
}

type recommendationServiceGetContentbasedDataClient struct {
	grpc.ClientStream
}

func (x *recommendationServiceGetContentbasedDataClient) Recv() (*ContentTile, error) {
	m := new(ContentTile)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *recommendationServiceClient) InitialRecommendationEngine(ctx context.Context, in *InitRecommendationRequest, opts ...grpc.CallOption) (*InitRecommendationResponse, error) {
	out := new(InitRecommendationResponse)
	err := c.cc.Invoke(ctx, "/RecommendationService.RecommendationService/InitialRecommendationEngine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommendationServiceServer is the server API for RecommendationService service.
type RecommendationServiceServer interface {
	TileClicked(context.Context, *TileClickedRequest) (*TileClickedResponse, error)
	GetCollabrativeFilteringData(*GetRecommendationRequest, RecommendationService_GetCollabrativeFilteringDataServer) error
	GetContentbasedData(*GetRecommendationRequest, RecommendationService_GetContentbasedDataServer) error
	InitialRecommendationEngine(context.Context, *InitRecommendationRequest) (*InitRecommendationResponse, error)
}

// UnimplementedRecommendationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRecommendationServiceServer struct {
}

func (*UnimplementedRecommendationServiceServer) TileClicked(ctx context.Context, req *TileClickedRequest) (*TileClickedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TileClicked not implemented")
}
func (*UnimplementedRecommendationServiceServer) GetCollabrativeFilteringData(req *GetRecommendationRequest, srv RecommendationService_GetCollabrativeFilteringDataServer) error {
	return status.Errorf(codes.Unimplemented, "method GetCollabrativeFilteringData not implemented")
}
func (*UnimplementedRecommendationServiceServer) GetContentbasedData(req *GetRecommendationRequest, srv RecommendationService_GetContentbasedDataServer) error {
	return status.Errorf(codes.Unimplemented, "method GetContentbasedData not implemented")
}
func (*UnimplementedRecommendationServiceServer) InitialRecommendationEngine(ctx context.Context, req *InitRecommendationRequest) (*InitRecommendationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitialRecommendationEngine not implemented")
}

func RegisterRecommendationServiceServer(s *grpc.Server, srv RecommendationServiceServer) {
	s.RegisterService(&_RecommendationService_serviceDesc, srv)
}

func _RecommendationService_TileClicked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TileClickedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).TileClicked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RecommendationService.RecommendationService/TileClicked",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).TileClicked(ctx, req.(*TileClickedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_GetCollabrativeFilteringData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRecommendationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecommendationServiceServer).GetCollabrativeFilteringData(m, &recommendationServiceGetCollabrativeFilteringDataServer{stream})
}

type RecommendationService_GetCollabrativeFilteringDataServer interface {
	Send(*ContentTile) error
	grpc.ServerStream
}

type recommendationServiceGetCollabrativeFilteringDataServer struct {
	grpc.ServerStream
}

func (x *recommendationServiceGetCollabrativeFilteringDataServer) Send(m *ContentTile) error {
	return x.ServerStream.SendMsg(m)
}

func _RecommendationService_GetContentbasedData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRecommendationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecommendationServiceServer).GetContentbasedData(m, &recommendationServiceGetContentbasedDataServer{stream})
}

type RecommendationService_GetContentbasedDataServer interface {
	Send(*ContentTile) error
	grpc.ServerStream
}

type recommendationServiceGetContentbasedDataServer struct {
	grpc.ServerStream
}

func (x *recommendationServiceGetContentbasedDataServer) Send(m *ContentTile) error {
	return x.ServerStream.SendMsg(m)
}

func _RecommendationService_InitialRecommendationEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).InitialRecommendationEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RecommendationService.RecommendationService/InitialRecommendationEngine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).InitialRecommendationEngine(ctx, req.(*InitRecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RecommendationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RecommendationService.RecommendationService",
	HandlerType: (*RecommendationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TileClicked",
			Handler:    _RecommendationService_TileClicked_Handler,
		},
		{
			MethodName: "InitialRecommendationEngine",
			Handler:    _RecommendationService_InitialRecommendationEngine_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCollabrativeFilteringData",
			Handler:       _RecommendationService_GetCollabrativeFilteringData_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetContentbasedData",
			Handler:       _RecommendationService_GetContentbasedData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "RecommendationService.proto",
}
